In [8]:
import os
import numpy as np
import face_recognition
import cv2
import pandas as pd
from datetime import datetime

In [9]:
#creating list for images and storing names
path='train images'
images=[]
classNames=[]

myLst=os.listdir(path)
print(myLst)

['Elon_Musk.jpg', 'MS-Dhoni.jpg', 'Subash_18MIS0222.jpg', 'test_dhoni.jpg']


In [10]:
#loading the images in the list and names in classNames

for cl in myLst:
    curImg=cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])

print(classNames)
    

['Elon_Musk', 'MS-Dhoni', 'Subash_18MIS0222', 'test_dhoni']


In [11]:
#Find the encodings

#create a function to find the encodings

def findEncodingd(images):
    #create an empty list to store the values of the enccodings
    encodeList=[]
    for img in images:
        img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        encode=face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    
    return encodeList

#create a functio0n to store the attendance 

def markAttendance(name):
    with open('Attendance.csv','r+') as f:
        myDataList=f.readlines()
        nameList=[]
        for line in myDataList:
            entry=line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now=datetime.now()
            dtString=now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{dtString}')

markAttendance('jack')

In [12]:
#Getting the encoding values for the images

myEncode=findEncodingd(images)
print('Encoding Complete and number of items encoded are : ',len(myEncode))

Encoding Complete and number of items encoded are :  4


In [ ]:
#Accessing the camera for recognising the face

cap=cv2.VideoCapture(0)

#Loop for Store the values

while True:
    
    #Reading the image from the video captured
    success,img=cap.read()
    
    #Set rhe Size and values for the images
    imgs=cv2.resize(img,(0,0),None,0.25,0.23)
    
    #Coverting the bgr image captured BGR to RGB
    imgs=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    
    
    #Finding the faces in the image
    faceCurFrame=face_recognition.face_locations(imgs)
    encodeCurFrame=face_recognition.face_encodings(imgs,faceCurFrame)
    
    #comparing the values with the stored list
    
    for encodeFace,faceLoc in zip(encodeCurFrame,faceCurFrame):
        result=face_recognition.compare_faces(myEncode,encodeFace)
        faceDistance=face_recognition.face_distance(myEncode,encodeFace)
        
        #Prints the encoding face distance
        print(faceDistance)
        
        matchIndex=np.argmin(faceDistance)
        
        if result[matchIndex]:
            name=classNames[matchIndex].upper()
            print(name)
            
            y1,x2,y2,x1=faceLoc
            
            #increase the size of the image as we reduced earlier
            y1,x2,y2,x1=y1*4,x2*4,y2*4,x1*4
            
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            markAttendance(name)
    cv2.imshow('Webcam',img)
    cv2.waitKey(1)

[0.72870001 0.75476253 0.49266525 0.70517022]
SUBASH_18MIS0222
[0.75130866 0.74315216 0.49577602 0.67574187]
SUBASH_18MIS0222
[0.76110688 0.72521198 0.49237071 0.67095818]
SUBASH_18MIS0222
[0.75317316 0.76352931 0.47006743 0.69773346]
SUBASH_18MIS0222
[0.76854715 0.79402093 0.51384949 0.75418154]
SUBASH_18MIS0222
[0.79599064 0.75790198 0.4868717  0.67781357]
SUBASH_18MIS0222
[0.72961886 0.77378507 0.51211587 0.71608094]
SUBASH_18MIS0222
[0.73838022 0.76959178 0.49531666 0.71077656]
SUBASH_18MIS0222
[0.75316393 0.75705842 0.43694515 0.69869785]
SUBASH_18MIS0222
[0.75492115 0.74790493 0.47073705 0.68944082]
SUBASH_18MIS0222
[0.77675467 0.72413143 0.46316803 0.68862847]
SUBASH_18MIS0222
[0.74458261 0.72562358 0.46855649 0.67357096]
SUBASH_18MIS0222
[0.78015377 0.74229966 0.47732393 0.69257611]
SUBASH_18MIS0222
[0.73677579 0.72326722 0.46209104 0.6996635 ]
SUBASH_18MIS0222
[0.73528209 0.78142168 0.51177614 0.73756852]
SUBASH_18MIS0222
[0.75572695 0.78134124 0.48964612 0.71403374]
SUBASH_18

[0.7746052  0.74453286 0.44048729 0.69273718]
SUBASH_18MIS0222
[0.78305296 0.77566446 0.48576054 0.72809625]
SUBASH_18MIS0222
[0.8062575  0.71248794 0.41032913 0.65883244]
SUBASH_18MIS0222
[0.75937598 0.74913598 0.46104636 0.70459916]
SUBASH_18MIS0222
[0.73664842 0.76418877 0.491801   0.70817776]
SUBASH_18MIS0222
[0.81308042 0.68284744 0.49095178 0.60856415]
SUBASH_18MIS0222
[0.84757729 0.74634519 0.44694629 0.71138048]
SUBASH_18MIS0222
[0.84818166 0.77673541 0.486057   0.69147433]
SUBASH_18MIS0222
[0.80563345 0.73615792 0.50010303 0.66939398]
SUBASH_18MIS0222
[0.8039596  0.70654838 0.47320811 0.62862908]
SUBASH_18MIS0222
[0.78986255 0.72802324 0.47191091 0.678246  ]
SUBASH_18MIS0222
[0.78428712 0.68904417 0.5001496  0.59582111]
SUBASH_18MIS0222
[0.80495608 0.72875005 0.57596732 0.67557606]
SUBASH_18MIS0222
[0.77239569 0.62320066 0.48555692 0.57720028]
SUBASH_18MIS0222
[0.8309702  0.73179207 0.52762997 0.68537751]
SUBASH_18MIS0222
[0.80653774 0.77486882 0.44657476 0.73415556]
SUBASH_18

[0.7394675  0.7818674  0.48752959 0.72028248]
SUBASH_18MIS0222
[0.75085676 0.77172357 0.49632872 0.7278853 ]
SUBASH_18MIS0222
[0.78859884 0.75960023 0.48745653 0.68593038]
SUBASH_18MIS0222
[0.78148051 0.73575842 0.49233604 0.69552627]
SUBASH_18MIS0222
[0.74742293 0.73029643 0.49660781 0.67568634]
SUBASH_18MIS0222
[0.73880991 0.70205319 0.52261677 0.6779014 ]
SUBASH_18MIS0222
[0.77376555 0.80192105 0.48248272 0.73238581]
SUBASH_18MIS0222
[0.7834862  0.80788671 0.48330109 0.74590921]
SUBASH_18MIS0222
[0.74807356 0.77334137 0.48692142 0.71719172]
SUBASH_18MIS0222
[0.79624051 0.78804731 0.49132752 0.73521547]
SUBASH_18MIS0222
[0.76818639 0.75354631 0.49451844 0.71442174]
SUBASH_18MIS0222
[0.76548302 0.71283722 0.46410419 0.67632368]
SUBASH_18MIS0222
[0.7516759  0.77890609 0.47612248 0.73820072]
SUBASH_18MIS0222
[0.77612789 0.8010879  0.53774277 0.76842675]
SUBASH_18MIS0222
[0.75102652 0.7662271  0.49616703 0.73675142]
SUBASH_18MIS0222
[0.76003403 0.7845094  0.53809786 0.72443465]
SUBASH_18

[0.74692101 0.70191139 0.47928456 0.63437747]
SUBASH_18MIS0222
[0.79111887 0.74275372 0.47662513 0.66325724]
SUBASH_18MIS0222
[0.78985697 0.79251689 0.4616368  0.74997394]
SUBASH_18MIS0222
[0.80933491 0.73162426 0.43942341 0.64034839]
SUBASH_18MIS0222
[0.79389193 0.73394446 0.42084122 0.66580716]
SUBASH_18MIS0222
[0.8359049  0.69774362 0.43223784 0.65796699]
SUBASH_18MIS0222
[0.80618183 0.7333042  0.42281913 0.66125707]
SUBASH_18MIS0222
[0.78665499 0.7401744  0.43005979 0.6820109 ]
SUBASH_18MIS0222
[0.782717   0.72722384 0.46738783 0.66596486]
SUBASH_18MIS0222
[0.7752746  0.69961359 0.47803017 0.64486144]
SUBASH_18MIS0222
[0.79873843 0.7210479  0.46991679 0.6513215 ]
SUBASH_18MIS0222
[0.78127114 0.737962   0.45547204 0.68608678]
SUBASH_18MIS0222
[0.76637884 0.72031376 0.46868585 0.67137245]
SUBASH_18MIS0222
[0.7771016  0.68037631 0.42785681 0.63919019]
SUBASH_18MIS0222
[0.76082678 0.73964036 0.42660643 0.67840012]
SUBASH_18MIS0222
[0.75796254 0.74544435 0.47706515 0.6821399 ]
SUBASH_18

[0.77041477 0.78190956 0.51725734 0.7464807 ]
SUBASH_18MIS0222
[0.79830908 0.78709701 0.48859083 0.73424095]
SUBASH_18MIS0222
[0.78114843 0.77597625 0.47450244 0.70557294]
SUBASH_18MIS0222
[0.78965458 0.74755119 0.51230796 0.7131109 ]
SUBASH_18MIS0222
[0.75262711 0.77360927 0.49955443 0.71407681]
SUBASH_18MIS0222
[0.77849664 0.78392705 0.49728207 0.73245553]
SUBASH_18MIS0222
[0.79690554 0.7643034  0.48732212 0.71142056]
SUBASH_18MIS0222
[0.77880299 0.75901418 0.50013556 0.69662377]
SUBASH_18MIS0222
[0.81831584 0.75144636 0.48903413 0.71703796]
SUBASH_18MIS0222
[0.76998628 0.73563159 0.49377765 0.66990692]
SUBASH_18MIS0222
[0.7566568  0.72263186 0.48762717 0.66837748]
SUBASH_18MIS0222
[0.78489091 0.75390907 0.44254871 0.70759886]
SUBASH_18MIS0222
[0.80779385 0.79361602 0.45285825 0.73393792]
SUBASH_18MIS0222
[0.77045683 0.80312855 0.4907737  0.74707729]
SUBASH_18MIS0222
[0.77108307 0.73410787 0.45362301 0.68621252]
SUBASH_18MIS0222
[0.74766378 0.74832987 0.41263699 0.68381984]
SUBASH_18

[0.83110076 0.79034253 0.49122067 0.71710406]
SUBASH_18MIS0222
[0.81296187 0.77352444 0.52114834 0.7161295 ]
SUBASH_18MIS0222
[0.79360137 0.77015967 0.47849609 0.69356217]
SUBASH_18MIS0222
[0.80892043 0.7798075  0.48163761 0.71307437]
SUBASH_18MIS0222
[0.80359587 0.76235503 0.50680635 0.69519685]
SUBASH_18MIS0222
[0.75024932 0.76602654 0.51028106 0.67782398]
SUBASH_18MIS0222
[0.8065904  0.77121729 0.49024855 0.69600027]
SUBASH_18MIS0222
[0.82461004 0.80681553 0.47926122 0.72691348]
SUBASH_18MIS0222
[0.8287274  0.78057592 0.49587616 0.71097278]
SUBASH_18MIS0222
[0.81494644 0.77212994 0.48793014 0.7161697 ]
SUBASH_18MIS0222
[0.81298357 0.77938246 0.50778647 0.72393922]
SUBASH_18MIS0222
[0.7934275  0.80465245 0.51864541 0.76241613]
SUBASH_18MIS0222
[0.79679384 0.77992321 0.51375689 0.68921749]
SUBASH_18MIS0222
[0.79900184 0.7721942  0.47468243 0.70551014]
SUBASH_18MIS0222
[0.83177124 0.73592973 0.49046549 0.67077173]
SUBASH_18MIS0222
[0.82872803 0.81117688 0.52473897 0.72144238]
SUBASH_18

[0.78875111 0.78975542 0.52238145 0.71920804]
SUBASH_18MIS0222
[0.81676679 0.81418569 0.51771041 0.74658488]
SUBASH_18MIS0222
[0.81561081 0.79713329 0.53387675 0.74593749]
SUBASH_18MIS0222
[0.81150224 0.81774087 0.52174101 0.74698602]
SUBASH_18MIS0222
[0.78253549 0.80216579 0.46664583 0.7403416 ]
SUBASH_18MIS0222
[0.80089391 0.76731776 0.47005016 0.69609077]
SUBASH_18MIS0222
[0.76207947 0.81365187 0.55709895 0.76363014]
SUBASH_18MIS0222
[0.78777579 0.82292409 0.5410268  0.74366941]
SUBASH_18MIS0222
[0.78917458 0.7783984  0.49472089 0.7010412 ]
SUBASH_18MIS0222
[0.76696399 0.81693055 0.52526033 0.76510087]
SUBASH_18MIS0222
[0.75760104 0.77283825 0.52193061 0.71885497]
SUBASH_18MIS0222
[0.7690949  0.76619612 0.51229144 0.71790624]
SUBASH_18MIS0222
[0.78420777 0.73219198 0.46723437 0.6679519 ]
SUBASH_18MIS0222
[0.79768597 0.73776237 0.48034878 0.70442614]
SUBASH_18MIS0222
[0.79791882 0.72428236 0.56189982 0.66181605]
SUBASH_18MIS0222
[0.75041481 0.75441621 0.57231604 0.66906547]
SUBASH_18

[0.80012067 0.79892149 0.52864482 0.71376499]
SUBASH_18MIS0222
[0.76076001 0.75667882 0.54109435 0.69292742]
SUBASH_18MIS0222
[0.82659342 0.80717708 0.49389646 0.74618069]
SUBASH_18MIS0222
[0.78998244 0.80685671 0.49866853 0.76117485]
SUBASH_18MIS0222
[0.78194641 0.80002381 0.52617291 0.74903823]
SUBASH_18MIS0222
[0.79721189 0.79642794 0.45982109 0.74451083]
SUBASH_18MIS0222
[0.76435139 0.80632894 0.5199188  0.73236284]
SUBASH_18MIS0222
[0.7678515  0.79590184 0.52379364 0.73389057]
SUBASH_18MIS0222
[0.74909113 0.80445612 0.52487914 0.73989654]
SUBASH_18MIS0222
[0.78532315 0.75347744 0.48535299 0.7227776 ]
SUBASH_18MIS0222
[0.77573269 0.77973678 0.50732631 0.70936661]
SUBASH_18MIS0222
[0.79870451 0.8296763  0.50014187 0.76174223]
SUBASH_18MIS0222
[0.80952502 0.82519629 0.52495275 0.75808002]
SUBASH_18MIS0222
[0.79645975 0.83952391 0.48810398 0.76069932]
SUBASH_18MIS0222
[0.75956113 0.83405147 0.5216422  0.76644328]
SUBASH_18MIS0222
[0.78256849 0.80688445 0.49370469 0.74936273]
SUBASH_18

[0.8136349  0.81011564 0.50179484 0.71838536]
SUBASH_18MIS0222
[0.80080588 0.78630025 0.50295676 0.73089743]
SUBASH_18MIS0222
[0.80057384 0.7797452  0.4638591  0.70215405]
SUBASH_18MIS0222
[0.77270994 0.78633382 0.47372082 0.71289607]
SUBASH_18MIS0222
[0.79937248 0.78876101 0.48522183 0.71119324]
SUBASH_18MIS0222
[0.76713424 0.7767602  0.47247339 0.70812808]
SUBASH_18MIS0222
[0.83034738 0.79396201 0.51782864 0.71846551]
SUBASH_18MIS0222
[0.77305718 0.74639935 0.51071705 0.69769635]
SUBASH_18MIS0222
[0.78981829 0.79224476 0.4667122  0.71091061]
SUBASH_18MIS0222
[0.7906178  0.7936296  0.47319549 0.7089313 ]
SUBASH_18MIS0222
[0.79572901 0.77935013 0.47725603 0.67982877]
SUBASH_18MIS0222
[0.73957263 0.79233779 0.50679836 0.7073787 ]
SUBASH_18MIS0222
[0.77454133 0.82147648 0.46981427 0.72963849]
SUBASH_18MIS0222
[0.7967371  0.83026699 0.50197156 0.75918059]
SUBASH_18MIS0222
[0.74477276 0.75175754 0.52804481 0.71035776]
SUBASH_18MIS0222
[0.75773424 0.75774787 0.50658238 0.69107971]
SUBASH_18

[0.77976893 0.73405812 0.45863525 0.70288234]
SUBASH_18MIS0222
[0.75411393 0.76216889 0.49434881 0.7378716 ]
SUBASH_18MIS0222
[0.75790187 0.75698731 0.48563424 0.69083768]
SUBASH_18MIS0222
[0.72807613 0.70946262 0.45710341 0.69052577]
SUBASH_18MIS0222
[0.77518467 0.70037235 0.46968003 0.67912252]
SUBASH_18MIS0222
[0.75366173 0.73493706 0.43376259 0.68569543]
SUBASH_18MIS0222
[0.77002288 0.74106216 0.43597605 0.68387762]
SUBASH_18MIS0222
[0.69317949 0.79599581 0.53441926 0.75457676]
SUBASH_18MIS0222
[0.72561101 0.78470663 0.50804885 0.74990059]
SUBASH_18MIS0222
[0.74742904 0.79775369 0.56167197 0.77721063]
SUBASH_18MIS0222
[0.76138417 0.78727939 0.51321429 0.74208052]
SUBASH_18MIS0222
[0.72702489 0.80018455 0.51519784 0.76228031]
SUBASH_18MIS0222
[0.74076079 0.75082289 0.50117645 0.72021412]
SUBASH_18MIS0222
[0.73227882 0.74066501 0.46300441 0.65240398]
SUBASH_18MIS0222
[0.71822726 0.73461085 0.43603112 0.69501931]
SUBASH_18MIS0222
[0.72260168 0.72879849 0.44303643 0.67228891]
SUBASH_18

In [6]:
df=pd.read_csv('Attendance.csv')
df.head()

<IPython.core.display.Javascript object>

Name      Time
0          MS-DHONI  18:53:15
1              jack  18:56:17
2  SUBASH_18MIS0222  18:56:49