In [2]:
import cv2
import numpy as np
import face_recognition

# import the train images 

In [28]:
trainImg=face_recognition.load_image_file('train images/MS-Dhoni.jpg')

#covert BGR Images to RGB using cv2
trainImg=cv2.cvtColor(trainImg,cv2.COLOR_BGR2RGB)

testImg=face_recognition.load_image_file('train images/test_dhoni.jpg')
testImg=cv2.cvtColor(testImg,cv2.COLOR_BGR2RGB)


In [29]:
#lOCATING THE FACE AND DETECTION

faceLoc=face_recognition.face_locations(trainImg)[0]
encode=face_recognition.face_encodings(trainImg)[0]

#gives the size of the rectangle of face located
print(faceLoc);

cv2.rectangle(trainImg,(faceLoc[3],faceLoc[0]),(faceLoc[1],faceLoc[2]),(255,0,255),2)


(59, 246, 122, 183)


array([[[126, 135, 155],
        [127, 136, 156],
        [127, 136, 156],
        ...,
        [ 92,  99, 118],
        [ 91,  97, 116],
        [ 90,  96, 115]],

       [[127, 136, 156],
        [127, 136, 156],
        [128, 137, 157],
        ...,
        [ 92,  99, 118],
        [ 92,  98, 117],
        [ 90,  96, 115]],

       [[127, 136, 156],
        [128, 137, 157],
        [128, 137, 157],
        ...,
        [ 93, 100, 119],
        [ 92,  98, 117],
        [ 90,  96, 115]],

       ...,

       [[140, 167, 188],
        [140, 167, 188],
        [140, 166, 190],
        ...,
        [129, 154, 174],
        [130, 155, 175],
        [131, 156, 176]],

       [[138, 165, 186],
        [137, 163, 187],
        [137, 163, 187],
        ...,
        [129, 153, 173],
        [130, 154, 174],
        [131, 155, 175]],

       [[132, 160, 184],
        [130, 158, 182],
        [130, 155, 181],
        ...,
        [134, 158, 178],
        [134, 158, 178],
        [133, 157, 177]]

In [31]:
faceLocTest=face_recognition.face_locations(testImg)[0]
encodeTest=face_recognition.face_encodings(testImg)[0]
cv2.rectangle(testImg,(faceLocTest[3],faceLocTest[0]),(faceLocTest[1],faceLocTest[2]),(255,0,255),2)

array([[[ 69,  80,  94],
        [ 70,  82,  94],
        [ 71,  83,  95],
        ...,
        [110, 141, 126],
        [112, 144, 127],
        [110, 144, 127]],

       [[ 69,  80,  94],
        [ 69,  81,  93],
        [ 70,  82,  94],
        ...,
        [116, 147, 132],
        [117, 149, 132],
        [116, 150, 133]],

       [[ 68,  80,  92],
        [ 68,  80,  92],
        [ 69,  81,  93],
        ...,
        [118, 149, 134],
        [117, 151, 134],
        [118, 152, 135]],

       ...,

       [[ 92, 183, 168],
        [ 93, 184, 169],
        [ 95, 186, 171],
        ...,
        [ 88, 186, 180],
        [ 88, 186, 180],
        [ 86, 186, 180]],

       [[ 88, 182, 165],
        [ 90, 184, 167],
        [ 92, 187, 167],
        ...,
        [ 92, 186, 181],
        [ 92, 186, 181],
        [ 92, 186, 181]],

       [[ 89, 183, 166],
        [ 91, 185, 168],
        [ 93, 188, 168],
        ...,
        [ 92, 186, 181],
        [ 92, 186, 181],
        [ 92, 186, 181]]

In [34]:
#Here we compare alist of images with the test 
#image with the encode values 
#Return True if matches or False

result=face_recognition.compare_faces([encode],encodeTest)
print(result)

[True]


In [55]:
#Compare another image with train image

testImg2=face_recognition.load_image_file('train images/Elon_Musk.jpg')
testImg2=cv2.cvtColor(testImg2,cv2.COLOR_BGR2RGB)
testFaceLoc=face_recognition.face_locations(testImg2)[0]
testEncode2=face_recognition.face_encodings(testImg2)[0]
print(testFaceLoc)

cv2.rectangle(testImg2,(testFaceLoc[3],testFaceLoc[0]),(testFaceLoc[1],testFaceLoc[2]),(255,0,255),2)

(139, 324, 325, 139)


array([[[184, 189, 188],
        [184, 189, 188],
        [184, 189, 188],
        ...,
        [176, 182, 181],
        [175, 181, 180],
        [175, 181, 180]],

       [[184, 189, 188],
        [184, 189, 188],
        [184, 189, 188],
        ...,
        [175, 181, 180],
        [175, 181, 180],
        [175, 181, 180]],

       [[184, 189, 188],
        [184, 189, 188],
        [184, 189, 188],
        ...,
        [175, 181, 180],
        [175, 181, 180],
        [175, 181, 180]],

       ...,

       [[ 26,  18,  18],
        [ 24,  16,  16],
        [ 24,  17,  14],
        ...,
        [ 33,  21,  21],
        [ 35,  23,  21],
        [ 39,  26,  24]],

       [[ 28,  18,  18],
        [ 27,  17,  17],
        [ 28,  18,  18],
        ...,
        [ 31,  19,  19],
        [ 34,  22,  22],
        [ 36,  23,  21]],

       [[ 32,  22,  22],
        [ 30,  20,  20],
        [ 31,  21,  21],
        ...,
        [ 30,  18,  18],
        [ 34,  22,  22],
        [ 35,  23,  23]]

In [51]:
result2=face_recognition.compare_faces([encode],testEncode2)
print(result2)

[False]


In [52]:
#Face Distance calculations

faceDis=face_recognition.face_distance([encode],encodeTest)

#True : Compare two same faces
print(result,faceDis)

[True] [0.42635705]


In [53]:
#False: Compare two different faces
faceDis2=face_recognition.face_distance([encode],testEncode2)
print(result2,faceDis2)

[False] [0.7841771]


In [59]:
#Print The Values in the Images
cv2.putText(trainImg,'Train Source Image',(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),2)

#TestImages
cv2.putText(testImg,f'{result} {faceDis}',(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),2)
cv2.putText(testImg2,f'{result2} {faceDis2}',(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),2)

array([[[184, 189, 188],
        [184, 189, 188],
        [184, 189, 188],
        ...,
        [176, 182, 181],
        [175, 181, 180],
        [175, 181, 180]],

       [[184, 189, 188],
        [184, 189, 188],
        [184, 189, 188],
        ...,
        [175, 181, 180],
        [175, 181, 180],
        [175, 181, 180]],

       [[184, 189, 188],
        [184, 189, 188],
        [184, 189, 188],
        ...,
        [175, 181, 180],
        [175, 181, 180],
        [175, 181, 180]],

       ...,

       [[ 26,  18,  18],
        [ 24,  16,  16],
        [ 24,  17,  14],
        ...,
        [ 33,  21,  21],
        [ 35,  23,  21],
        [ 39,  26,  24]],

       [[ 28,  18,  18],
        [ 27,  17,  17],
        [ 28,  18,  18],
        ...,
        [ 31,  19,  19],
        [ 34,  22,  22],
        [ 36,  23,  21]],

       [[ 32,  22,  22],
        [ 30,  20,  20],
        [ 31,  21,  21],
        ...,
        [ 30,  18,  18],
        [ 34,  22,  22],
        [ 35,  23,  23]]

In [60]:
cv2.imshow('Dhoni',trainImg)
cv2.imshow('test Dhoni',testImg)
cv2.imshow('Elon Musk',testImg2)

cv2.waitKey(0)

-1